name: tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Run linters
        run: |
          pip install ruff
          ruff check .
          ruff format --check --diff .