name: tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run linters
        run: |
          pip install ruff pyright
          pip install -e .[dev]
          ruff check .
          ruff format --check --diff .
          pyright
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python:
          - '3.10'
          - '3.13'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Run tests
        run: |
          python -m pip install -U pip
          pip install .[dev]
          python -m pytest --capture=no
        shell: bash
